#:schema node_modules/wrangler/config-schema.json
name = "federation-count"
main = "src/index.js"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]

workers_dev = false

routes = [
	{ pattern = "floofy.tech/api/vfloof/peerCount", zone_name = "floofy.tech" }
]